enum Partner {
  GOODREADS
}
enum NudgeDirection {
  UP
  DOWN
}

type Query {
  medias: [Media!]
  posts: [Post!]
  groups: [Group!]
  users: [User!]
  findUserByEmail(emailAddress: String!): User
  findGroupByName(name: String!, isInPublicDirectory: Boolean!): [Group!]
}

type Media {
  name: String!
  author: String!
  imageUrl: String!
  publicationDate: Date
  partner: Partner
  partnerId: String
}

type Post {
  nudges: [Nudge!] @relation
  user: User!
  text: String!
  date: Time!
  replyTo: Post @relation(name: "replyTo")
  replies: [Reply!] @relation
  reading: Reading
  group: Group!
  link: Link
}

type Reply {
  reply: Post @relation
}

type User {
  givenName: String!
  familyName: String!
  emailAddress: String! @unique
  posts: [Post!]
  groups: [Group!]
  nominations: [Nomination!]
  nudges: [Nudge!]
  refreshTokens: [RefreshToken!] @relation
  roles: [Role!]
}

type Nudge {
  user: User!
  direction: NudgeDirection!
  post: Post!
}

type MeetingResponse {
  user: User!
  isAttending: Boolean
  meeting: Meeting! @relation
}

type Meeting {
  startDateTime: Time!
  endDateTime: Time!
  description: String!
  addressLine1: String
  addressLine2: String
  city: String
  state: String
  group: Group!
  attendance: [MeetingResponse!] @relation
  readings: [Reading!]
}

type Reading {
  position: Int
  nomimation: Nomination!
  posts: [Post!]
  votes: [Vote!]
  meeting: Meeting!
}

type RefreshToken {
  user: User! @relation
  expirationDate: Time!
  token: String!
}

type Election {
  group: Group!
  nominations: [Nomination!]
  startDateTime: Time
  endDateTime: Time
}

type Vote {
  user: User!
  value: Int
  nomination: Nomination
  reading: Reading
}

type Nomination {
  pitchedBy: User!
  date: Time!
  media: Media!
  votes: [Vote!]
  group: Group!
  election: Election!
  reading: Reading
}

type Group {
  name: String! @unique
  users: [User!]
  nominations: [Nomination!]
  elections: [Election!]
  isInPublicDirectory: Boolean!
}

type Link {
  post: Post!
  description: String
  image: String
  title: String
  url: String!
  type: String
  siteName: String
}

type Role {
  name: String! @unique
  users: [User!]
  group: Group
}
